project:
  type: website

website:
  title: "aakash basnet"
  back-to-top-navigation: true
  reader-mode: false
  navbar:
    title: false
    logo: "core/assets/images/profile.jpg"
    background: primary
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: core//blog.qmd
      - text: "About"
        href: core/about.qmd
      - text: "Contact"
        href: core/contact.qmd
      - icon: github
        href: https://github.com/hssaka7
      - icon: linkedin
        href: https://www.linkedin.com/in/aakash-basnet-a889a120a/

  page-footer:
    background: dark
    border: false
    center: 
      - text: "Copyright 2024, Aakash Basnet" 
      - icon: github
        href: https://github.com/hssaka7
      - icon: linkedin
        href: https://www.linkedin.com/in/aakash-basnet-a889a120a/
    
format:
  html:
    theme:
      dark: darkly
      light: flatly
      
    css: core/assets/css/style.css
    toc: true


